[profile.default]
src = "src"
out = "out"
libs = ["lib"]
rempapings = ['@openzeppelin/contracts=lib/openzeppelin-contracts/contracts']
optimizer = true
optimizer_runs = 200
via_ir = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
